name: Build and deploy Python project to Azure Function App - func-backup

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './BlobReplicatorFunction'  
  PYTHON_VERSION: '3.12'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9871D46992414356B6F0F8D80287AF11 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5006897C8F324FCCA98DDCFD6289020A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A3F56ACE917447EC8C3D855B596EABB5 }}

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'func-backup'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          app-settings: |
            PRIMARY_STORAGE_CONNECTION_STRING=${{ secrets.PRIMARY_STORAGE_CONNECTION_STRING }}
            SECONDARY_STORAGE_CONNECTION_STRING=${{ secrets.SECONDARY_STORAGE_CONNECTION_STRING }}
            SECONDARY_CONTAINER_NAME=${{ secrets.SECONDARY_CONTAINER_NAME }}
